baseURL: https://archittportfoliowebsite.netlify.app/
languageCode: en-us
title: Architt's Portfolio Website 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's Go
    subtitle: This is a website about me and my work
    title: Hi, My name is Architt. 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Baker street  
        # title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: akedia.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 1800 002 002
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Architt Kedia
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/architt.kedia/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/archiekedia/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Archittkedia/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://in.linkedin.com/in/architt-kedia-lbs2022
  image: ''
  name: Architt Kedia
  navigation:
    # button1:
    #   - name: Get Started
    #     url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/Architt
      - name: About Me
        url: blogs/work
      - name: R Project
        url: blogs/project
        
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Dive in to find about more about my life
        title: About Me
        url: blogs/architt
      - image: pic08.jpg
        subtitle: Dive in to find out about my Academic work
        title: My Work
        url: blogs/Work
      - image: pic09.jpg
        subtitle: Find about more about my R project
        title: R project
        url: blogs/project
  two:
    buttonText: Resume
    enable: yes
    title: Download my Resume
    url: https://drive.google.com/file/d/1t2JWmXFCOtEFaD7TxS-jLfmdS0NaOVWP/view?usp=sharing
